services:
  postgres:
    image: postgres:16-alpine
    container_name: visa-d-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: visa-d-database
    ports:
      - "5432:5432"
    volumes:
      - visa_d_pgdata:/var/lib/postgresql/data

volumes:
  visa_d_pgdata:
